// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxtKZCM2TpC2ZikzCSpQB0tzO32RBVZOQ',
    appId: '1:289988108309:web:32c8c4611e174be0982e1c',
    messagingSenderId: '289988108309',
    projectId: 'class-26-june',
    authDomain: 'class-26-june.firebaseapp.com',
    storageBucket: 'class-26-june.appspot.com',
    measurementId: 'G-FH0RC2STHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKH5lfbhOqcvr8IIX1Q56FYvfiFiDPqt8',
    appId: '1:289988108309:android:d8ab04324fb72301982e1c',
    messagingSenderId: '289988108309',
    projectId: 'class-26-june',
    storageBucket: 'class-26-june.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZycHmWDWwFJP0l8YNC9tE5he9_gS9WVM',
    appId: '1:289988108309:ios:f31fe2d9bed482b2982e1c',
    messagingSenderId: '289988108309',
    projectId: 'class-26-june',
    storageBucket: 'class-26-june.appspot.com',
    iosClientId: '289988108309-m19iecjms2fguh022i5m8bkqesegr8nq.apps.googleusercontent.com',
    iosBundleId: 'com.example.class26june',
  );
}
